class_name CardLibrary

var card_list:Dictionary={}

func _init():
	# ideally we don't have an individual file in the library folder for every card
	# -- some can be autogenerated
	
	var json=JSON.parse_string(FileAccess.get_file_as_string("res://cards/cards.json"))	
	for line in json:
		var id=line.id
		var path = "res://cards/library/"+id.to_lower()+".gd"
		if(id=="BGEchoForm"):
			var bp=0
		if(FileAccess.file_exists(path)):
			card_list[id]=load(path).new().setup(line)
		else:
			card_list[id]=AbstractCard.new().setup(line)
	
	#for id in card_list:		
		#var card:Dictionary = card_list[id]
		#if(card.has("quickimplementation")):
			#var tags = card.quickimplementation.split(";")		
			#print(id," ",tags)
			#for tag in tags:
				#var params = tag.split("=")
				##print(params[0])
				#var path="res://cards/cardscript/tags/card_tag_"+params[0].to_lower()+".gd"
				##print(path)
				#if(ResourceLoader.exists(path)):
					#pass
					##print(path," exists");
				#else:
					#print("Tag not found: ",params[0])
